# Form implementation generated from reading ui file 'C:\Users\Desired\PycharmProjects\ProjectNhom\giaodien.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from tkinter.tix import Form

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(728, 615)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(170, 40, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pbtgieo = QtWidgets.QPushButton(parent=Form)
        self.pbtgieo.setGeometry(QtCore.QRect(290, 230, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pbtgieo.setFont(font)
        self.pbtgieo.setObjectName("pbtgieo")
        self.lneketqua = QtWidgets.QLineEdit(parent=Form)
        self.lneketqua.setGeometry(QtCore.QRect(360, 400, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.lneketqua.setFont(font)
        self.lneketqua.setObjectName("lneketqua")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(130, 400, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Chương trình gieo xúc xắc"))
        self.pbtgieo.setToolTip(_translate("Form", "Nhấn để gieo"))
        self.pbtgieo.setText(_translate("Form", "Gieo xúc xắc"))
        self.label_2.setText(_translate("Form", "Kết quả gieo ngẫu nhiên là:"))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui = MainWindow()
    ui.show()
    app.exec()