# Form implementation generated from reading ui file 'C:\Users\Desired\PycharmProjects\ProjectNhom\GUItest.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btngieo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btngieo.setGeometry(QtCore.QRect(310, 230, 75, 23))
        self.btngieo.setObjectName("btngieo")
        self.lnketqua = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnketqua.setGeometry(QtCore.QRect(310, 300, 113, 20))
        self.lnketqua.setObjectName("lnketqua")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btngieo.setText(_translate("MainWindow", "PushButton"))
